# coding=utf-8

BACKEND = 1
FRONTEND = 2
JUMP_SERVER_IP = '127.0.0.1'
CODE_DIR = '/web/code'
DOCKER_SERVER = []

ALIYUN_OSS_ACCESS_KEY_ID = 'xxx'
ALIYUN_OSS_ACCESS_KEY_SECRET = 'xxx'

HEPLUS_URL = "url"
