FROM docker.elastic.co/elasticsearch/elasticsearch:6.2.3

#CMD mv /usr/share/elasticsearch/config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml.bak

#CMD chown elasticsearch

EXPOSE 9200 9300

